language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: xkAkJ9PqZRJBsABsJN3QRSBabMCr6lcmoTFjrBitr3wYawmATfxfHWJ+BD1Vf5vNHCx99YnvTh3NBVI+LOIYXJ1chPDx9MuC/3z8kXR608hnNCbqIvKrn/ap8SbtwhtOeHcOdGB1S+efahaBJk/sKnpKFd9veDrM6X2GKk98WdV7fMlNfkF0RlgK7g+8ZqvyS3EDcQq8srw5ZCl8p4ZziAxYDQM0VCZzMmuKPT15xFdB3oHelTuKwlGEfwS7Ypg18Nb+8W5poX4Xk5/aUvGyjz37KFcms902XhSNx2CfGzDvSdzAhHS+wkUbGNK9CYf+f5ta/zYGV2tzE1jdchW38rFIivFMXwgu/n/gxVAPXk2kgH60ywOYqZFoS9lYpXlmgZ5e4NFPJ8SFCHDPyo1LEtjV3p48yNBMOL7TPg0cZF8j8OKOK7DibS/UMFwQsNDiXDT/iYB1vtY81jDY+g7z0DHa8TszMpHzqqkP+ycZsfxLElpzy7paMeBGljeeEL7pfPv6obbPbgxz8oTrUbeUkQLWewrotRh8AM6bc4AbiR3aQL4LHHKhLuQ2jEfJQtmst2kP7vGo+FRvP1GTVnDS4pwTYoKGkIsYcBZSRCYSYch1yHGz4xKbEu7llAHIZykGvPWpYuXHEBqKZqOKjO3IKwG4M/EyiPk/6A1W5nOSDh0=
  app: agile-stream-26405
