language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: NdFno8sruuqKveMzWtTSw9hfNjrZ5nQ2VTq5c+aVe383GQ+nRG2DNalhDOLIbsfmgNXPFxmGREaAXNI8C1S5GhKf8gPaU6VJhXIZDaDuqb+nFLFKftlTECr8sKBMOeCQMBMkz0ApREEOOT8azJJhBOnmsryGLj6Mj/GulvSgPRm7dxwA8fO0u1PRtK3VLHr5nz7kWHJr+mO2FGhb/Mh1YBGl9B81xC1aXuBWOAGOlKGmQYh/Lrz6cUa/To/YfWUXzYzcWpiKnhS9j/JoTEsoLO6TjhbE5pAi0rKxGCeE2vK3CxysvDAHA6qYpXLgrgmPSHUkKyaqcUiHFSDOGi8JUj3vZ40t+FygMOa9aR3RnCNJl9rJv+EXrKz3bO2lPaUXwEF3jnimMcWHsz4xLNjPG0IxyKAzh62FodYLQlzGaAtk33md4ajaRPa/B23kYdZECVgMxNSxU9LVk59NQjCl+J1VfvXKGIrPXQI1TawMZJXbhlmXwmnL3g+qy0qpjMdYsEr/VXYz4Ngd/7IFVaLIJJIDLHbm7VGuGmNRpy4obojOJzNLxl4genfKnVJf8T2rA1ueJIvWrWvNY/A5hMYP2GF7bJVYoqXuv21HD63gFFhIXyCGxbquPlNahpJC8/5kKtpNg1u66sb9NKgnp9g8YzGEdiN9fY9+7E4GlkmK0jY=
  app: agile-stream-26405
  on:
    repo: codeannie/guestbook-api
