language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: V/aCLdpLY4bKJDKq/5D7pgCcWNUFH7WRluWGH64IADEMxe94+kLeH3PKNBhzjgUvIKLw+dOA/v5CvTA4Q2TCzvE6HKgZuUrtTpb+sk0/+SOXMDqNDIwsnZsTqB5mapCA8DisMGdHCGQU+yzU1WwdZoCOzKDTp3V+94yp0i+i7wzfHb9ZQR+vGqisDrsFwUSJZbl+lTKakwGwLs5iaPyYqB0PFJRtgQTq/kD1sfJG1vMAKj9sTOJZB8+xysl1PpCUcB7lNsaEQGMZz0Un8XNwiIwFUJYpIOk3XBVo2PF17WuQhJQh447BdLYBSkRqSZUEUcsDoMPL0JykS82ZfMRbuCfNcb0k9ZMp7kMxMo1Dj/1Dm9LQMNV726Jt2llWmnf+jFxxhcJDDQFCKd0E/PND2HPq5GSLwwO3rUzplzMXrFwlrrBOpRdgZq9ui8fPEuAcY/NfKZJ2hKMuFLbCQY3JPlgSgBdkNkRZje85Z4GaMXr+xWLME/pkeTty8+sqGa+XgFk0CMl2AnNw6in0kcZoGidqcAjfifE+XnZF0tNurRC3553puNHU+VKbUzm8fJ2zRskq74hsVUDZu3/Sqd/qjzrMH1fiJ6v0exn6+asH8YXIuBxbPBzkjzj6RzEsjH+oGHQhJvza5a7WYWce21ZFQ/O17FHpiEa/VXFVQpMpmmE=
  app: agile-stream-26405
  on:
    repo: codeannie/guestbook-api
