language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: nLOTdS7yu3Xl5tsZGETNRBM7Jz2pFQMjJkBc/FYmr9as4zJzc9V4GP76yUmE3MdvsJ0KxkTo90HsTm/N5KVbludBwvRWLJQ6NsRdNreL1MX4uT9Ey7u8dNKnT53LTD2PcL71yfFvpDxaLwGTpP51d+rUW9iprmcl1CCGlwwW/AZ7Rwm7QVJ4TprRkC9qrrQYnTF3Vz7PIDkWNPfDpJ2XrLvCqEMWVDiFQUL3esjPn21u0Xwn4wyaGaFCPLCEcxpsXvigrMLGrVHiop92/3PT15MtR58b1BGNY6LH4sDcwleVDHIefOhROab1VSyfqYZuzz3JRnejBJFKdy5mwFJHGV75zjkuYrGPCwdsE5n1/vc6k4e1E+m67IwiRE/bcm9NARU7VzXVxwYMsC530LGBahxyIDO+QRyUT/9cn/quJfFy7+FLoNZ6YR/Hz6NYmX3QnNn1LScXhnJ1YMqJKOldyuX3L6hnfU6UkgViaWoNcqnOJs0ieMuq1LC5EpvQZLG4pSfEQA/ssTKc4qQO2GZzz+TINwl+3GKVyKQ+N4MYMG9LPFYmOGSBrAJOivYIef/t7h1L7ozWE6DZ+s7PhViYrcMpAnB/NOs6ELBgDPKrwbZ9G8xP0C3uZKtqxN7aaI+CyMkK7T8AiElpEXIXrlxGW6tjN2P8QiI6gyPQCsausB0=
  app: agile-stream-26405
